"""Animated HomeStar idents - three distinct treatments, 1.6s each.

Every reel currently ends on a static navy card. That card works, but it is
inert: it reads as the video stopping rather than finishing.

    python build_ident.py            all three
    python build_ident.py level      just one

Deliberately NOT generated by an AI video model. A brand mark has to come out
identical on every render, at the exact navy and the exact green, in the real
typeface. A generative model gives a slightly different mark each time, which
is precisely what an ident must not do. Built from the brand assets with PIL,
so it is deterministic.

THE THREE:

  rule    Typographic and quiet. The short green rule wipes out from the
          centre, the wordmark rises, the strapline settles as its letter
          spacing closes. Closest to the existing end card, so it costs the
          brand nothing to adopt.

  level   A green laser line sweeps the full width and reveals the wordmark
          as it passes, then retracts into the short rule. The reference is
          the laser line used to keep tile courses true - F9's caption names
          it. Of the three this is the only one that means something.

  trowel  An angled edge sweeps bottom-left to top-right, revealing the mark
          the way a trowel passes over a wall. Carries the STRAPLINE IN GREEN,
          to answer that question directly rather than in the abstract.

ON THE GREEN STRAPLINE, since it was asked: the recommendation is white, and
`trowel` exists so the two can be compared rather than argued about. Two
reasons. The green is an accent and works because it appears exactly once -
put it on the strapline and it appears twice, so it stops accenting anything
and starts being a second body colour. And brand green on navy is a far
weaker contrast than white on navy at strapline size, which matters most on
the small, dim phone screens where these are actually seen.

Silent on purpose. The audio logo cannot be made with the tooling here - see
the note at the bottom of this file.
"""

import os
import re
import subprocess
import sys

import imageio_ffmpeg
from PIL import Image, ImageDraw, ImageFilter, ImageFont

import build_ads as BRAND

FF = imageio_ffmpeg.get_ffmpeg_exe()
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "renders", "ident")
FONTS = os.path.join(HERE, "fonts")

W, H, FPS = 1080, 1920, 30
S = 2
DUR = 1.6
N = int(DUR * FPS)

VARIANTS = ("rule", "level", "trowel")


def font(name, size):
    return ImageFont.truetype(os.path.join(FONTS, name), size * S)


def ease(t):
    t = min(1.0, max(0.0, t))
    return t * t * (3 - 2 * t)


def window(frame, start, end):
    t0, t1 = start * FPS, end * FPS
    if frame <= t0:
        return 0.0
    if frame >= t1:
        return 1.0
    return ease((frame - t0) / float(t1 - t0))


def ground(cw, ch):
    img = Image.new("RGB", (cw, ch), BRAND.NAVY_DARK).convert("RGBA")
    glow = Image.new("RGBA", (cw, ch), (0, 0, 0, 0))
    ImageDraw.Draw(glow).ellipse([cw * 0.02, ch * 0.24, cw * 0.98, ch * 0.76],
                                 fill=BRAND.NAVY + (52,))
    img.alpha_composite(glow.filter(ImageFilter.GaussianBlur(int(150 * S))))
    return img


def mark_layer(cw, ch, cy, alpha=255, rise=0, strap_alpha=0, strap_extra=0.0,
               strap_green=False):
    """The wordmark and strapline on a transparent layer."""
    layer = Image.new("RGBA", (cw, ch), (0, 0, 0, 0))
    d = ImageDraw.Draw(layer)
    cx = cw // 2

    f = font("PlusJakartaSans-ExtraBold.ttf", 78)
    text = "HOMESTAR"
    tw = d.textlength(text, font=f)
    d.text((cx - tw / 2, cy + rise), text, font=f, fill=BRAND.WHITE + (alpha,))

    if strap_alpha > 0:
        fs = font("PlusJakartaSans-Medium.ttf", 26)
        strap = "SERVICES & CONTRACTING"
        widths = [d.textlength(c, font=fs) + strap_extra for c in strap]
        x = cx - sum(widths) / 2
        colour = BRAND.GREEN if strap_green else BRAND.WHITE
        for c, wdt in zip(strap, widths):
            d.text((x, cy + int(104 * S)), c, font=fs,
                   fill=colour + (strap_alpha,))
            x += wdt
    return layer


def frame_rule(i, cw, ch):
    img = ground(cw, ch)
    d = ImageDraw.Draw(img)
    cx, cy = cw // 2, int(ch * 0.46)

    p = window(i, 0.00, 0.30)
    half = int(int(78 * S) * p / 2)
    if half > 0:
        y = cy - int(64 * S)
        d.rectangle([cx - half, y, cx + half, y + int(7 * S)], fill=BRAND.GREEN)

    p = window(i, 0.20, 0.70)
    q = window(i, 0.55, 0.95)
    if p > 0:
        img.alpha_composite(mark_layer(
            cw, ch, cy, alpha=int(255 * p), rise=int((1 - p) * 26 * S),
            strap_alpha=int(205 * q), strap_extra=(1 - q) * 10 * S))
    return img


def frame_level(i, cw, ch):
    """A laser line sweeps the width, revealing the mark, then retracts."""
    img = ground(cw, ch)
    cx, cy = cw // 2, int(ch * 0.46)
    ry = cy - int(64 * S)

    sweep = window(i, 0.00, 0.55)
    retract = window(i, 0.60, 0.90)
    strap = window(i, 0.75, 1.10)

    # The mark, revealed only to the left of the travelling line.
    full = mark_layer(cw, ch, cy, alpha=255,
                      strap_alpha=int(205 * strap))
    mask = Image.new("L", (cw, ch), 0)
    edge = int(cw * sweep)
    if edge > 0:
        ImageDraw.Draw(mask).rectangle([0, 0, edge, ch], fill=255)
        mask = mask.filter(ImageFilter.GaussianBlur(int(14 * S)))
        full.putalpha(Image.composite(full.getchannel("A"),
                                      Image.new("L", (cw, ch), 0), mask))
        img.alpha_composite(full)

    # The line itself: full width while sweeping, then pulling in to the rule.
    d = ImageDraw.Draw(img)
    # Only while the sweep is actually travelling. Drawing it during the
    # retract left a stray vertical line pinned to the right edge for the rest
    # of the clip.
    if sweep < 1.0:
        x = edge
        d.rectangle([max(0, x - int(3 * S)), 0, x, ch], fill=BRAND.GREEN + (210,))
    half_full, half_rule = cw // 2, int(78 * S) // 2
    half = int(half_full + (half_rule - half_full) * retract)
    if retract > 0:
        d.rectangle([cx - half, ry, cx + half, ry + int(7 * S)], fill=BRAND.GREEN)
    return img


def frame_trowel(i, cw, ch):
    """An angled edge sweeps bottom-left to top-right. Strapline in green."""
    img = ground(cw, ch)
    cx, cy = cw // 2, int(ch * 0.46)
    ry = cy - int(64 * S)

    p = window(i, 0.05, 0.75)
    strap = window(i, 0.70, 1.05)

    plate = Image.new("RGBA", (cw, ch), (0, 0, 0, 0))
    pd = ImageDraw.Draw(plate)
    pd.rectangle([cx - int(78 * S) // 2, ry, cx + int(78 * S) // 2,
                  ry + int(7 * S)], fill=BRAND.GREEN)
    plate.alpha_composite(mark_layer(cw, ch, cy, alpha=255,
                                     strap_alpha=int(205 * strap),
                                     strap_green=True))

    # Diagonal reveal. The first version's polygon was already covering the
    # whole canvas on frame one, so the mark simply appeared - no wipe at all.
    # The half-plane x + y < T is a right triangle from the origin, and moving
    # T from 0 to cw+ch sweeps it diagonally across the frame.
    mask = Image.new("L", (cw, ch), 0)
    md = ImageDraw.Draw(mask)
    T = int((cw + ch) * p)
    md.polygon([(-20, -20), (T, -20), (-20, T)], fill=255)
    mask = mask.filter(ImageFilter.GaussianBlur(int(20 * S)))
    plate.putalpha(Image.composite(plate.getchannel("A"),
                                   Image.new("L", (cw, ch), 0), mask))
    img.alpha_composite(plate)
    return img


BUILDERS = {"rule": frame_rule, "level": frame_level, "trowel": frame_trowel}


def build(variant):
    cw, ch = W * S, H * S
    frames_dir = os.path.join(HERE, "_ident_%s" % variant)
    os.makedirs(frames_dir, exist_ok=True)
    os.makedirs(OUT, exist_ok=True)

    fn = BUILDERS[variant]
    for i in range(N):
        fn(i, cw, ch).convert("RGB").resize((W, H), Image.LANCZOS).save(
            os.path.join(frames_dir, "%04d.png" % i))

    dst = os.path.join(OUT, "homestar-ident-%s.mp4" % variant)
    subprocess.run([FF, "-y", "-hide_banner", "-loglevel", "error",
                    "-framerate", str(FPS),
                    "-i", os.path.join(frames_dir, "%04d.png"),
                    "-c:v", "libx264", "-preset", "slow", "-crf", "16",
                    "-pix_fmt", "yuv420p", "-r", str(FPS), dst], check=True)
    for f in os.listdir(frames_dir):
        os.remove(os.path.join(frames_dir, f))
    os.rmdir(frames_dir)

    # Verify size AND duration, not merely that a file appeared.
    err = subprocess.run([FF, "-i", dst], capture_output=True, text=True).stderr
    assert "%dx%d" % (W, H) in err, "wrong size: %s" % dst
    m = re.search(r"Duration: (\d+):(\d+):([\d.]+)", err)
    got = int(m.group(1)) * 3600 + int(m.group(2)) * 60 + float(m.group(3))
    assert abs(got - DUR) < 0.15, "%s is %.2fs" % (dst, got)
    print("  %-7s %dx%d  %.2fs  %.2f MB" % (variant, W, H, got,
                                            os.path.getsize(dst) / 1048576))
    return dst


# ---------------------------------------------------------------------------
# The audio logo cannot be made with the tools available here.
#
# Higgsfield's audio tooling is text-to-SPEECH only. Its music and sound-effect
# models are documented as belonging to a game-generation pipeline and
# explicitly not for standalone audio, so reaching for them would be misusing
# them. There is no general music model exposed.
#
# The right home is Mureka, which Eric already uses for every music bed - which
# also keeps the audio logo under the same ownership as the rest of the music,
# so it stays clear for YouTube and the website.
#
# Spec for Mureka:
#   - 1.2 to 1.6 seconds, ending cleanly with no tail
#   - three notes, rising, resolving on the root
#   - warm and wooden: marimba, kalimba or soft plucked string. Not synth
#     brass, not a whoosh, nothing that sounds like a tech company
#   - one voice only. It has to survive a phone speaker at low volume
#   - the same key across every variant, so it sits under any music bed
#   - delivered dry, no reverb tail, so it times exactly to the ident
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    wanted = [a for a in sys.argv[1:] if a in VARIANTS] or list(VARIANTS)
    for v in wanted:
        build(v)
