"""A 1.6-second animated HomeStar ident.

Every reel currently ends on a static navy card with the wordmark on it. That
card does its job, but it is inert - it looks like the video stopped rather
than finished. This is the same mark, drawn on.

Deliberately NOT generated by an AI video model. The brand mark is a fixed
thing: it should come out identical every time, at the exact brand navy and
the exact brand green, with the real typeface. A generative model would give
a slightly different mark on every render, which is the opposite of what an
ident is for.

    python build_ident.py

Writes renders/ident/homestar-ident.mp4 (1080x1920, silent).

The timing is the whole design:
    0.00-0.30  the green rule wipes out from the centre
    0.20-0.70  HOMESTAR rises and fades up
    0.55-0.95  SERVICES & CONTRACTING settles in behind it
    0.95-1.60  hold

Silent on purpose. The audio logo is a separate piece of work and cannot be
made with the tools here - see the note at the bottom of this file.
"""

import os
import subprocess

import imageio_ffmpeg
from PIL import Image, ImageDraw, ImageFilter, ImageFont

import build_ads as BRAND

FF = imageio_ffmpeg.get_ffmpeg_exe()
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "renders", "ident")
FRAMES = os.path.join(HERE, "_ident_frames")
FONTS = os.path.join(HERE, "fonts")

W, H, FPS = 1080, 1920, 30
S = 2
DUR = 1.6
N = int(DUR * FPS)


def font(name, size):
    return ImageFont.truetype(os.path.join(FONTS, name), size * S)


def ease(t):
    """smoothstep - zero gradient at both ends, so nothing snaps."""
    t = min(1.0, max(0.0, t))
    return t * t * (3 - 2 * t)


def window(frame, start, end):
    """Progress through an animation window, 0 before it and 1 after."""
    t0, t1 = start * FPS, end * FPS
    if frame <= t0:
        return 0.0
    if frame >= t1:
        return 1.0
    return ease((frame - t0) / float(t1 - t0))


def draw_frame(i):
    cw, ch = W * S, H * S
    img = Image.new("RGB", (cw, ch), BRAND.NAVY_DARK).convert("RGBA")

    # A very slight navy lift toward the centre, so the flat colour has depth.
    # Blurred hard - unblurred it reads as a visible ellipse drawn on the
    # background rather than as light.
    glow = Image.new("RGBA", (cw, ch), (0, 0, 0, 0))
    gd = ImageDraw.Draw(glow)
    gd.ellipse([cw * 0.02, ch * 0.24, cw * 0.98, ch * 0.76],
               fill=BRAND.NAVY + (52,))
    glow = glow.filter(ImageFilter.GaussianBlur(int(150 * S)))
    img.alpha_composite(glow)

    d = ImageDraw.Draw(img)
    cx, cy = cw // 2, int(ch * 0.46)

    # 1. The rule wipes outward from the centre.
    p = window(i, 0.00, 0.30)
    full = int(78 * S)
    half = int(full * p / 2)
    if half > 0:
        d.rectangle([cx - half, cy - int(64 * S),
                     cx + half, cy - int(64 * S) + int(7 * S)],
                    fill=BRAND.GREEN)

    # 2. The wordmark rises into place.
    p = window(i, 0.20, 0.70)
    if p > 0:
        f = font("PlusJakartaSans-ExtraBold.ttf", 78)
        text = "HOMESTAR"
        tw = d.textlength(text, font=f)
        rise = int((1 - p) * 26 * S)
        layer = Image.new("RGBA", (cw, ch), (0, 0, 0, 0))
        ld = ImageDraw.Draw(layer)
        ld.text((cx - tw / 2, cy + rise), text, font=f,
                fill=BRAND.WHITE + (int(255 * p),))
        img.alpha_composite(layer)

    # 3. The line beneath settles in.
    p = window(i, 0.55, 0.95)
    if p > 0:
        f = font("PlusJakartaSans-Medium.ttf", 26)
        text = "SERVICES & CONTRACTING"
        # Letter-spacing closes as it arrives, which reads as settling rather
        # than simply appearing.
        extra = (1 - p) * 10 * S
        widths = [d.textlength(c, font=f) + extra for c in text]
        x = cx - sum(widths) / 2
        layer = Image.new("RGBA", (cw, ch), (0, 0, 0, 0))
        ld = ImageDraw.Draw(layer)
        for c, wdt in zip(text, widths):
            ld.text((x, cy + int(104 * S)), c, font=f,
                    fill=BRAND.WHITE + (int(205 * p),))
            x += wdt
        img.alpha_composite(layer)

    return img.convert("RGB").resize((W, H), Image.LANCZOS)


def main():
    os.makedirs(FRAMES, exist_ok=True)
    os.makedirs(OUT, exist_ok=True)
    for i in range(N):
        draw_frame(i).save(os.path.join(FRAMES, "%04d.png" % i))

    dst = os.path.join(OUT, "homestar-ident.mp4")
    subprocess.run([FF, "-y", "-hide_banner", "-loglevel", "error",
                    "-framerate", str(FPS), "-i", os.path.join(FRAMES, "%04d.png"),
                    "-c:v", "libx264", "-preset", "slow", "-crf", "16",
                    "-pix_fmt", "yuv420p", "-r", str(FPS), dst], check=True)

    for f in os.listdir(FRAMES):
        os.remove(os.path.join(FRAMES, f))
    os.rmdir(FRAMES)

    # Verify size AND duration, not just that a file appeared.
    err = subprocess.run([FF, "-i", dst], capture_output=True, text=True).stderr
    assert "%dx%d" % (W, H) in err, "wrong size"
    import re
    m = re.search(r"Duration: (\d+):(\d+):([\d.]+)", err)
    got = int(m.group(1)) * 3600 + int(m.group(2)) * 60 + float(m.group(3))
    assert abs(got - DUR) < 0.15, "%.2fs, wanted %.2f" % (got, DUR)
    print("wrote %s  %dx%d  %.2fs  %d frames  %.2f MB"
          % (os.path.basename(dst), W, H, got, N, os.path.getsize(dst) / 1048576))


# ---------------------------------------------------------------------------
# The audio logo cannot be made with the tools available here.
#
# Higgsfield's audio tooling is text-to-SPEECH only. Its music and sound-effect
# models are documented as belonging to a game-generation pipeline and
# explicitly not for standalone audio, so reaching for them would be misusing
# them. There is no general music model exposed.
#
# The right home for it is Mureka, which Eric already uses for every music bed
# in the library - which also keeps the audio logo under the same ownership as
# the rest of the music, so it stays clear for YouTube and the website.
#
# Spec to give Mureka:
#   - 1.2 to 1.6 seconds, ending cleanly with no tail
#   - three notes, rising, resolving on the root
#   - warm and wooden - marimba, kalimba or soft plucked string. Not synth
#     brass, not a whoosh, nothing that sounds like a tech company
#   - one voice only. It has to survive a phone speaker at low volume
#   - same key across every variant so it can sit under any music bed
#   - deliver dry, no reverb tail, so it can be timed exactly to this ident
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    main()
